# Generated by Django 5.2.3 on 2025-06-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the category (e.g., 'Electronics', 'Books')", max_length=255, unique=True, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product', null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=10, verbose_name='Price')),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current stock level of the product', verbose_name='Stock Quantity')),
                ('image', models.ImageField(blank=True, help_text='Upload a product image file', null=True, upload_to='products/', verbose_name='Product Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The category this product belongs to', on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
